platform: x64

environment:
  GH_TOKEN:
    secure: NuR1Pg/kiQENELxE4St2Y155NCtUa75EBKeyNTVL7U+vCRa0Oui32XI00jXTEY/J
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - '%USERPROFILE%\.electron'
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn
  - cd app && yarn && cd ..

build_script:
  - yarn dist -- --win --x64 --ia32

test: off
